# Virtual Hosts
#
# Required modules: mod_log_config

<VirtualHost *:80>
    ServerName jackson-brain.com
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =music.jackson-brain.com
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
    ServerName jackson-brain.com
    DocumentRoot "/var/www/vhosts/jackson-brain.com"

    ErrorLog /var/log/httpd/musicbox.error.log
    CustomLog /var/log/httpd/musicbox.access.log combined
    LogLevel warn

    # Ampache/Subsonic API requires the Authorization header to be forwarded
    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
    Header Set Access-Control-Allow-Origin "https://jackson-brain.com"

    <Directory "/var/www/vhosts/jackson-brain.com">
        AllowOverride All
    </Directory>

    SetEnv APPLICATION_ENV "production"

    SSLCertificateFile    /etc/letsencrypt/live/jackson-brain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/jackson-brain.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
