# AirSonic Advanced reverse proxy
# Internal backend: http://localhost:8080

<VirtualHost *:80>
    ServerAdmin jack@jackson-brain.com
    ServerName music.jackson-brain.com
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =music.jackson-brain.com
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin jack@jackson-brain.com
    ServerName music.jackson-brain.com
    ErrorLog  "/var/log/httpd/airsonic_proxy-error_log"
    CustomLog "/var/log/httpd/airsonic_proxy-access_log" common

    SSLEngine on
    SSLProtocol all -SSLv3
    SSLProxyProtocol all -SSLv3
    SSLHonorCipherOrder on
    SSLCipherSuite PROFILE=SYSTEM
    SSLProxyCipherSuite PROFILE=SYSTEM

    <Location />
        Order allow,deny
        Allow from all
        Header set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.gstatic.com; img-src 'self' *.akamaized.net; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; frame-src 'self'; object-src 'none'"
    </Location>

    # WebSocket support (used by AirSonic UI)
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*)           ws://localhost:8080/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /(.*)           http://localhost:8080/$1 [P,L]

    <IfModule mod_proxy.c>
        SSLProxyEngine On
        ProxyRequests Off
        ProxyPass        / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/
        Header always set Strict-Transport-Security "max-age=604800"
        RequestHeader set X-Forwarded-Proto "https"
    </IfModule>

    Include /etc/letsencrypt/options-ssl-apache.conf
    # Wildcard cert *.jackson-brain.com
    SSLCertificateFile    /etc/letsencrypt/live/jackson-brain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/jackson-brain.com/privkey.pem
</VirtualHost>
